title: Lyfemmetry
description: Blog for geoscience researchings
author: Aigerim Sultanbekova & Joan Cano
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/lifemmetry/LifemmetryR
about: Geeks

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
